export { isBlocked, unresolvedBlockingChildIds } from "./blocking.js";
export { isEffectivelySatisfied } from "./convergence.js";
export type { DomainError } from "./errors.js";
export {
  activateBlockingChild,
  activateNode,
  addCoreQuestion,
  addCriterion,
  addEvidence,
  closeNode,
  completePass,
  createBlockingChild,
  createChild,
  createProject,
  declareCriterionSatisfied,
  ensureProjectRoot,
  evaluateConvergence,
  focusNode,
  linkEvidenceToCriterion,
  markChildBlocking,
  moveCandidateToFrontier,
  parkNode,
  promoteFrontierItem,
  reopenNode,
  resumeNode,
  returnToParent,
  setNodeSummary,
  unmarkChildBlocking,
  updateProjectMetadata,
} from "./operations.js";
export { defaultPorts } from "./ports.js";
export type { Ports } from "./ports.js";
export {
  CORE_QUESTION_LIMIT,
  migratedProjectRootId,
  PROJECT_ROOT_ORIENTATION_GOAL,
  type ActivateBlockingChild,
  type ActivateNode,
  type AddCoreQuestion,
  type AddCriterion,
  type AddEvidence,
  type CloseNode,
  type ConvergenceEvaluation,
  type CreateBlockingChild,
  type CreateChild,
  type CreateProject,
  type Criterion,
  type CriterionId,
  type DeclareCriterionSatisfied,
  type DomainEvent,
  type DomainResult,
  type DomainSnapshot,
  type EnsureProjectRoot,
  type Evidence,
  type FocusNode,
  type FrontierItem,
  type FrontierPlacement,
  type LearningNode,
  type LearningPass,
  type LearningProject,
  type LearningDepth,
  type LinkEvidenceToCriterion,
  type MarkChildBlocking,
  type NodeId,
  type MoveCandidateToFrontier,
  type NodeLifecycle,
  type ParkNode,
  type PassId,
  type ProjectId,
  type PromoteFrontierItem,
  type ReopenEvent,
  type ReopenNode,
  type ResumeNode,
  type SetNodeSummary,
  type UnmarkChildBlocking,
  type UpdateProjectMetadata,
} from "./types.js";
