export {
  activeProjects,
  applyNodeDragStop,
  applySelectedCommand,
  archiveProject,
  closeChat,
  createWorkspace,
  createWorkspaceProject,
  deleteArchivedProject,
  followCurrentNode,
  focusAndOpenInspector,
  moveFloatingChat,
  normalizeChatBindings,
  normalizeWorkspaceSelection,
  openChat,
  openChatForNode,
  pinChatToNode,
  restoreProject,
  selectProject,
  selectedProject,
  setChatPlacement,
  setInspectorOpen,
  setSelectedViewport,
  updateSelectedLayout,
  updateShell,
  updateWorkspaceProjectMetadata,
  archivedProjects,
  workspaceFromSnapshot,
} from "./session.js";
export {
  ARCHIVED_COLLAPSE_THRESHOLD,
  clampArchivedPaneHeight,
  clampChatWidth,
  clampInspectorWidth,
  clampSidebarWidth,
  COLLAPSED_SIDEBAR_WIDTH,
  DEFAULT_ARCHIVED_PANE_HEIGHT,
  DEFAULT_CHAT_WIDTH,
  DEFAULT_COLOR_SCHEME,
  DEFAULT_INSPECTOR_WIDTH,
  DEFAULT_LOCALE,
  DEFAULT_SIDEBAR_WIDTH,
  DEFAULT_VIEWPORT,
  defaultChatLayout,
  defaultProjectLayout,
  defaultShell,
  initialFloatingChatPosition,
  MAX_ARCHIVED_PANE_HEIGHT,
  MAX_CHAT_WIDTH,
  MAX_INSPECTOR_WIDTH,
  MAX_SIDEBAR_WIDTH,
  MIN_ACTIVE_PANE_HEIGHT,
  MIN_ARCHIVED_PANE_HEIGHT,
  MIN_CHAT_WIDTH,
  MIN_INSPECTOR_WIDTH,
  MIN_SIDEBAR_WIDTH,
  resolveArchivedRelease,
  resolveColorScheme,
  resolveSidebarRelease,
  SIDEBAR_COLLAPSE_THRESHOLD,
  WORKSPACE_PREFERENCES_KEY,
  WORKSPACE_PREFERENCES_KEY_V1,
  WORKSPACE_SEMANTIC_KEY,
  WORKSPACE_THEME_HINT_KEY,
} from "./defaults.js";
export {
  mergeNodePositions,
  resolveNodePosition,
} from "./layout.js";
export {
  applyStoredPreferences,
  createMemoryPreferenceStorage,
  hydrateWorkspacePreferences,
  loadWorkspacePreferences,
  parseStoredPreferences,
  readThemeHint,
  reconcileThemeHint,
  saveWorkspacePreferences,
  serializeWorkspacePreferences,
  writeThemeHint,
} from "./preferences.js";
export {
  hydrateSemanticWorkspace,
  hydrateSemanticWorkspaceWithMigration,
  loadSemanticWorkspace,
  loadSemanticWorkspaceWithMigration,
  parseSemanticWorkspace,
  saveSemanticWorkspace,
  serializeSemanticWorkspace,
} from "./persistence/semantic.js";
export { LAYOUT_VERSION, SEMANTIC_VERSION } from "./types.js";
export type {
  ChatBinding,
  ChatPlacement,
  ChatPosition,
  ChatPositionOrigin,
  ColorScheme,
  LearningWorkspace,
  NodePosition,
  PaneReleaseResult,
  PreferenceStorage,
  ProjectWorkspace,
  ProjectWorkspaceLayout,
  ResolvedColorScheme,
  StoredWorkspacePreferences,
  StoredWorkspaceSemantics,
  Viewport,
  WorkspaceErrorOrigin,
  WorkspaceLocale,
  WorkspaceShellLayout,
} from "./types.js";
export type {
  CreateWorkspaceProjectOptions,
  DeleteArchivedProjectResult,
} from "./session.js";
export type { NodeId, ProjectId } from "../application/index.js";
