export {
  BOOTSTRAP_PIPELINE,
  CANONICAL_CONTRACT_ID,
  CANONICAL_CONTRACT_VERSION,
  defaultDefinitionOfDone,
  EXPLORATION_BUDGET,
  LEARNING_TREE_ADAPTER_ID,
  LEARNING_TREE_ADAPTER_VERSION,
  LEGACY_FRAMEWORK_ID,
  PROJECT_LEARNING_FRAMEWORK_ID,
  PROJECT_LEARNING_FRAMEWORK_VERSION,
  type AdapterId,
  type AdapterVersion,
  type BootstrapPipelineStage,
  type CanonicalContractId,
  type CanonicalContractVersion,
  type CoreQuestionRole,
  type DefinitionOfDoneTemplate,
  type ExplorationBudget,
  type FrameworkId,
  type FrameworkVersion,
  type LearningDepth,
  type QuestionContract,
} from "./contract.js";
export {
  deriveRepositoryEvidence,
  EVIDENCE_STATUSES,
  isEvidenceStatus,
  normalizeRepositoryEvidence,
  parseGitHubSource,
  type EvidenceInput,
  type EvidenceStatus,
  type GitHubRepositoryRef,
  type PackageJsonEvidence,
  type RepositoryEvidence,
  type RepositoryEvidenceSource,
  type RepositoryMetadata,
} from "./evidence.js";
export {
  classifyDiscovery,
  type DiscoveryClassification,
  type DiscoveryDestination,
} from "./classify.js";
export {
  defaultTargetDepthForRole,
  runProjectLearningBootstrap,
  type ProjectLearningProposal,
  type ProposedCoreQuestion,
} from "./bootstrap.js";
